const Accounts = [
  {
    id: "1",
    username: "alfy",
    email: "alfyatun@gmail.com",
    password: "alfy",
    role: "supervisor",
  },
  {
    id: "2",
    username: "aly",
    email: "aly@gmail.com",
    password: "aly",
    role: "operator",
  },
  {
    id: "3",
    username: "afy",
    email: "afygmail.com",
    password: "afy",
    role: "operator",
  },
  {
    id: "4",
    username: "al",
    email: "al@gmail.com",
    password: "al",
    role: "operator",
  },
  {
    id: "5",
    username: "usma",
    email: "usma@gmail.com",
    password: "usma",
    role: "supervisor",
  },
  {
    id: "6",
    username: "ahmad",
    email: "ahmad@gmail.com",
    password: "alfy",
    role: "operator",
  },
  {
    id: "7",
    username: "karina",
    email: "karina@gmail.com",
    password: "karina",
    role: "operator",
  },
  {
    id: "8",
    username: "dita",
    email: "dita@gmail.com",
    password: "dita",
    role: "operator",
  },
  {
    id: "9",
    username: "mawar",
    email: "mawar@gmail.com",
    password: "mawar",
    role: "operator",
  },
  {
    id: "10",
    username: "ulfa",
    email: "ulfa@gmail.com",
    password: "ulfa",
    role: "operator",
  },
  {
    id: "11",
    username: "piti",
    email: "piti@gmail.com",
    password: "piti",
    role: "operator",
  },
  {
    id: "12",
    username: "siska",
    email: "siska@gmail.com",
    password: "siska",
    role: "operator",
  },
  {
    id: "13",
    username: "tofa",
    email: "tofa@gmail.com",
    password: "tofa",
    role: "operator",
  },
  {
    id: "14",
    username: "facri",
    email: "fachrialfajar@gmail.com",
    password: "fachri",
    role: "operator",
  },
  {
    id: "15",
    username: "sri",
    email: "sri@gmail.com",
    password: "sri",
    role: "operator",
  },
  {
    id: "16",
    username: "susi",
    email: "susi@gmail.com",
    password: "susi",
    role: "operator",
  },
  {
    id: "17",
    username: "muna",
    email: "muna@gmail.com",
    password: "muna",
    role: "operator",
  },
  {
    id: "18",
    username: "kyky",
    email: "kyky@gmail.com",
    password: "kyky",
    role: "operator",
  },
  {
    id: "19",
    username: "yanto",
    email: "yanto@gmail.com",
    password: "yanto",
    role: "operator",
  },
  {
    id: "20",
    username: "bejo",
    email: "bejo@gmail.com",
    password: "bejo",
    role: "operator",
  },
]
export default Accounts;